
export const dadJokes = [
  "I'm afraid for the calendar. Its days are numbered.",
  "What do you call a fish with no eyes? Fsh.",
  "I don't trust stairs. They're always up to something.",
  "Why did the scarecrow win an award? Because he was outstanding in his field.",
  "What do you call a factory that makes okay products? A satisfactory.",
  "What do you call a boomerang that won't come back? A stick.",
  "Why don't skeletons fight each other? They don't have the guts.",
  "I told my wife she was drawing her eyebrows too high. She looked surprised.",
  "What's the best thing about Switzerland? I don't know, but the flag is a big plus.",
  "I invented a new word! Plagiarism!",
  "Did you hear about the restaurant on the moon? Great food, no atmosphere.",
  "Why did the bicycle fall over? Because it was two tired!",
  "What do you call a lazy kangaroo? Pouch potato.",
  "I asked the librarian if the library had any books on paranoia. She whispered, 'They're right behind you!'",
  "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
  "What do you get when you cross a snowman and a vampire? Frostbite.",
  "Why are elevator jokes so classic? They work on many levels.",
  "I'm on a seafood diet. I see food and I eat it.",
  "Why don't scientists trust atoms? Because they make up everything!",
  "What do you call a magic dog? A labracadabrador.",
  "How does a penguin build its house? Igloos it together.",
  "I would avoid the sushi if I was you. It’s a little fishy.",
  "Want to hear a joke about construction? I'm still working on it.",
  "What do you call a can opener that doesn't work? A can't opener.",
  "I used to be a baker, but I couldn't make enough dough.",
  "Why did the scarecrow get promoted? He was outstanding in his field.",
  "What do you call a sad strawberry? A blueberry.",
  "Why did the invisible man turn down the job offer? He couldn't see himself doing it.",
  "I told my computer I needed a break, and now it won’t stop sending me Kit-Kat ads.",
  "What do you call an alligator in a vest? An investigator.",
  "Why was the math book sad? It had too many problems.",
  "I have a joke about time travel, but you didn't like it.",
  "What do you call a pile of cats? A meowtain.",
  "I'm reading a book on anti-gravity. It's impossible to put down!",
  "Why was the bee's hair sticky? He used a honeycomb.",
  "What did the janitor say when he jumped out of the closet? Supplies!",
  "What do you call a sleeping bull? A bulldozer.",
  "I wanted to go on a diet, but I feel like I have too much on my plate right now.",
  "Why can't a bicycle stand up by itself? It's two tired.",
  "Did you hear about the guy who invented the knock-knock joke? He won the 'no-bell' prize.",
  "I don't play soccer because I enjoy the sport. I'm just in it for the kicks.",
  "What did the grape do when he got stepped on? He let out a little wine.",
  "Why did the tomato turn red? Because it saw the salad dressing!",
  "I used to hate facial hair, but then it grew on me.",
  "What did one wall say to the other? I'll meet you at the corner.",
  "How do you make a tissue dance? You put a little boogie in it.",
  "What do you call a cheese that isn't yours? Nacho cheese.",
  "Why did the cookie go to the doctor? Because it felt crummy.",
  "What did the ocean say to the beach? Nothing, it just waved.",
  "I have a fear of speed bumps, but I'm slowly getting over it.",
  "What's orange and sounds like a parrot? A carrot.",
  "Why did the coffee file a police report? It got mugged.",
  "How do you organize a space party? You planet.",
  "I’m so good at sleeping, I can do it with my eyes closed.",
  "Why do we tell actors to 'break a leg?' Because every play has a cast.",
  "Why was the stadium so cool? It was full of fans.",
  "What did the drummer call his twin daughters? Anna one, Anna two!",
  "Why do bees have sticky hair? Because they use a honeycomb.",
  "What kind of shoes do ninjas wear? Sneakers.",
  "What's a vampire's favorite fruit? A neck-tarine.",
  "I went to a restaurant that served 'breakfast at any time.' So I ordered French toast during the Renaissance.",
  "What do you call a snowman with a six-pack? An abdominal snowman.",
  "Why did the picture go to jail? It was framed.",
  "What do you call a bear with no teeth? A gummy bear.",
  "Why couldn't the pony sing a lullaby? She was a little hoarse.",
  "I thought about going on an all-almond diet. But that's just nuts.",
  "Why do you never see elephants hiding in trees? Because they're so good at it.",
  "What is an astronaut's favorite part of a computer? The space bar.",
  "Why are ghosts such bad liars? Because you can see right through them.",
  "What did the left eye say to the right eye? Between you and me, something smells.",
  "What do you call a fake noodle? An impasta.",
  "Why did the scarecrow win an award? He was outstanding in his field.",
  "I don't have a joke about my new glasses. I just can't see it yet.",
  "What do you call a dog that can do magic? A Labracadabrador.",
  "Did you hear about the claustrophobic astronaut? He just needed a little space.",
  "Why did the student eat his homework? Because the teacher told him it was a piece of cake.",
  "What do you call a ship that has a leak? A sink.",
  "What’s the difference between a poorly dressed man on a tricycle and a well-dressed man on a bicycle? Attire.",
  "What did the police officer say to his belly button? You're under a vest.",
  "Why did the belt get arrested? For holding up a pair of pants.",
  "What did one hat say to the other? You stay here, I'm going on ahead.",
  "Why do crabs never give to charity? Because they're shellfish.",
  "What do you get from a pampered cow? Spoiled milk.",
  "Why did the man get fired from the calendar factory? He took a couple of days off.",
  "Why did the chewing gum cross the road? It was stuck to the chicken's foot.",
  "What's brown and sticky? A stick.",
  "Why can't you hear a pterodactyl go to the bathroom? Because the 'P' is silent.",
  "What do you call a pig that does karate? A pork chop.",
  "Why did the cow go to outer space? To see the mooooooon.",
  "What is a computer's favorite snack? Computer chips.",
  "How do you make holy water? You boil the hell out of it.",
  "What do you call a man with a rubber toe? Roberto.",
  "Why don't some couples go to the gym? Because some relationships don't work out.",
  "What do you call a fish wearing a bowtie? Sofishticated.",
  "What did the big flower say to the little flower? Hi, bud!",
  "Why was the broom late? It over-swept.",
  "What's a pirate's favorite letter? You think it's 'R' but it be the 'C'.",
  "Why did the music teacher need a ladder? To reach the high notes.",
  "What do you call a belt made out of watches? A waist of time.",
  "Why can't you trust an atom? They make up everything.",
  "How do you tell the difference between a crocodile and an alligator? You will see one later and one in a while.",
  "What's a skeleton's least favorite room in the house? The living room.",
  "I don't trust those trees. They seem a bit shady.",
  "My wife asked me to stop singing 'Wonderwall' to her. I said maybe...",
  "What do you call a short, psychic dwarf who has escaped from prison? A small medium at large.",
  "I used to be addicted to soap, but I'm clean now.",
  "What did the shark say when he ate the clownfish? This tastes a little funny.",
  "Why did the syrup have a hard time at the party? It was too thick to mingle.",
  "A man tells his doctor, 'Doc, help me. I’m addicted to Twitter!' The doctor replies, 'Sorry, I don’t follow you.'",
  "What do you call a guy who's really loud? Mike.",
  "Why did the bicycle quit the race? It was two tired.",
  "Why did the can crusher quit his job? It was soda pressing.",
  "What's the best time on a clock? 6:30, hands down.",
  "How do you find Will Smith in the snow? You look for the fresh prints.",
  "I'm terrified of elevators. I'm going to start taking steps to avoid them.",
  "I got a new job at a library, but it's not what I expected. I'm checking out.",
  "Why did the blind man fall into the well? Because he couldn't see that well.",
  "I'm not a fan of stairs. They're always up to something.",
  "What do you call a musician with a problem? A trebled man.",
  "Why do chicken coops only have two doors? Because if they had four, they would be a chicken sedan.",
  "What's the difference between a guitar and a fish? You can't tuna fish.",
  "Why did the old man fall in the well? Because he couldn't see that well.",
  "I wanted to learn how to drive a stick shift, but I couldn't find a manual.",
  "I'm writing a book. I've got the page numbers done.",
  "What did the ranch say when someone opened the refrigerator door? 'Hey, close the door! I'm dressing!'",
  "Why are there gates around cemeteries? Because people are dying to get in.",
  "What did the policeman say to his stomach? 'Freeze. You're under a vest.'",
  "Why are some people scared of hurdles? It's a mental block.",
  "Why is it a bad idea to iron your four-leaf clover? Because you shouldn't press your luck.",
  "I'm thinking about removing my spine. I feel like it's holding me back.",
  "My wife told me to take the spider out instead of killing it. We went and had a few drinks. Cool guy. Wants to be a web developer.",
  "Where do you learn to make ice cream? Sundae school.",
  "Why did the football coach go to the bank? To get his quarterback.",

  "What did the nut say when it was chasing the other nut? I'm a cashew!",
  "Why did the tree go to the dentist? It needed a root canal.",
  "What do you call a fly without wings? A walk.",
  "Why did the astronaut break up with his girlfriend? He needed some space.",
  "Why is 'dark' spelled with a 'k' and not a 'c'? Because you can't 'c' in the dark.",
  "What do you call a group of disorganized cats? A cat-tastrophe.",
  "Why do we have to wait until night to call it a day?",
  "What has four wheels and flies? A garbage truck.",
  "Why do cows wear bells? Because their horns don't work.",
  "Why did the scarecrow get a promotion? Because he was outstanding in his field.",
  "What did the zero say to the eight? Nice belt.",
  "What's the best way to watch a fly-fishing tournament? Live stream.",
  "What did the fish say when he swam into the wall? Dam.",
  "Why did the hipster burn his tongue? He drank his coffee before it was cool.",
  "Why did the man run around his bed? To catch up on his sleep.",
  "What do you call an empty bottle of soda? A pop-tart.",
  "What did the buffalo say to his son when he left for college? Bison.",
  "Why do you never find elephants hiding in trees? Because they're so good at it.",
  "What’s the best part about living in Switzerland? I don’t know, but the flag is a big plus.",
  "What is the leading cause of dry skin? Towels.",
  "Why don't they play poker in the jungle? Too many cheetahs.",
  "What did the grape say when it got crushed? Nothing, it just let out a little wine.",

  "Why are there fences around graveyards? Because people are dying to get in.",
  "Why did the melon jump into the lake? It wanted to be a water-melon.",
  "What did the horse say after it tripped? 'Help! I've fallen and I can't giddyup!'",
  "Why did the farmer win an award? He was outstanding in his field.",
  "How do you get a squirrel to like you? Act like a nut.",
  "What do you call a cheese that isn't yours? Nacho cheese.",
  "Why did the student get an F on his report card? Because he couldn't draw a straight line.",
  "Why do bees have sticky hair? Because they use a honeycomb.",
  "What do you call a lazy baby kangaroo? Pouch potato.",
  "Why was the computer cold? It left its Windows open.",
  "Why did the clock go on a diet? It was trying to lose some weight.",
  "What do you call a man who can't stand? Neil.",
  "Why did the boy bring a ladder to the bar? He heard the drinks were on the house.",
  "Why was the belt arrested? For holding up a pair of pants.",
  "Why did the phone get a bad review? It had too many hang-ups.",
  "What do you call a person who is a sour winner? A lemon-aid.",
  "Why are skeletons so calm? Because nothing gets under their skin.",
  "Why did the traffic light turn red? You would too if you had to change in the middle of the street.",
  "Why did the tomato blush? Because it saw the salad dressing.",
  "What did one plate say to the other plate? Dinner is on me.",
  "Why did the photographer get kicked out of the party? He kept taking candid shots.",
  "What do you call a fake noodle? An Impasta.",
  "Why do we park on driveways and drive on parkways?",
  "What did the triangle say to the circle? You're pointless.",
  "Why do scuba divers fall backwards into the water? Because if they fell forwards they'd still be in the boat.",
  "What do you call a sleeping pizza? A pi-zzzz-a.",
  "What did the ocean say to the pirate? Nothing, it just waved.",
  "What is a tornado's favorite game? Twister.",
  "Why did the scarecrow go to the doctor? He was feeling a little straw-nge.",
  "Why are teddy bears never hungry? They are always stuffed.",
  "What did the sea say to the iceberg? Nothing, it just waved.",
  "Why do we tell actors to break a leg? Because every play has a cast.",
  "What do you call a naughty lamb? A baaad sheep.",
  "Why did the frog call his insurance company? He had a jump in his car.",
  "Why did the mushroom go to the party? Because he was a fungi.",
  "Why did the cookie go to the hospital? Because it felt crummy.",
  "What do you call a sad cup of coffee? Depresso.",
  "Why did the picture go to jail? It was framed.",
  "How do you make a lemon drop? Just let it fall.",
  "Why do you have to be odd to be number one?",
  "What's a foot long and slippery? A slipper.",
  "Why did the man put his money in the freezer? He wanted cold hard cash.",
  "What's an alligator's favorite drink? Gator-ade.",
  "Why can't you give Elsa a balloon? Because she will let it go.",
  "Why don't eggs tell jokes? They'd crack each other up.",
  "Why was the baby strawberry crying? Because his parents were in a jam.",
  "What do you call a lazy person in a car? A car-pet.",
  "What's a pirate's favorite exercise? The plank.",
  "Why did the math book look so sad? Because of all its problems.",
  "Why can't a bicycle stand up for itself? It's two-tired.",
  "What did the shoe say to the hat? You go on ahead, I'll follow on foot.",
  "Why did the cow have a long face? Because it was moo-dy.",
  "Why don't some fish play piano? You can't tuna fish.",
  "How do you throw a party in space? You planet.",
  "What do you call a person who is good at holding a grudge? A grudge-holder.",
  "Why was the book sad? Because it had a bad ending.",
  "Why did the bicycle get a timeout? It was two-tired.",
  "Why did the chair get a promotion? It was outstanding in its field.",
  "What do you call a snowman in July? A puddle.",
  "Why did the coffee file a police report? It got mugged.",
  "What did one eye say to the other? Between you and me, something smells.",
  "Why did the calendar get a bad review? Its days were numbered.",
  "What do you call a bear with no ears? B.",
  "Why did the man get hit by a bike every day? He was stuck in a vicious cycle.",
  "What do you call a deer with no eyes? No eye-deer.",
  "What do you call a deer with no eyes and no legs? Still no eye-deer.",
  "Why did the nurse need a red pen? In case she needed to draw blood.",
  "What's a computer's favorite beat? An algo-rhythm.",
  "Why did the sun go to school? To get brighter.",
  "What do you call a writer who can't stop writing? A pen-addict.",
  "Why was the picture kicked out of the bar? It was too graphic.",
  "Why did the girl throw a clock out the window? She wanted to see time fly.",
  "Why did the man quit his job at the donut factory? He was fed up with the hole business.",
  "What do you call a person who is afraid of Santa? A Claus-trophobic.",
  "Why did the farmer have to separate the chickens and the turkeys? He sensed fowl play.",
  "Why did the girl wear a helmet to dinner? She was on a crash diet.",
  "What do you call a snake that is exactly 3.14 meters long? A pi-thon.",
  "Why was the student's report card wet? It was below C-level.",
  "What do you call a person who has a contagious laugh? A laugh-y person.",
  "Why did the police officer write a ticket to the ghost? It didn't have a haunting license.",
  "Why do we have to sleep? Because we're not allowed to do it at work.",
  "What did the paper say to the pencil? Write on!",
  "Why did the tree break up with the bush? It was tired of being a little bushed.",
  "Why did the student get a bad grade on his test? He was a little off.",
  "Why was the music teacher so good at her job? She had a lot of class.",
  "What do you call a person who is always on time? A punctual person.",
  "Why did the man get a job at the bakery? He kneaded the dough.",
  "Why did the boy throw his clock out the window? He wanted to see time fly.",
  "Why did the bicycle get a flat tire? It was two-tired.",
  "Why did the student get a bad grade on his test? He was a little off.",
  "Why was the music teacher so good at her job? She had a lot of class.",
  "What do you call a person who is always on time? A punctual person.",
  "Why did the man get a job at the bakery? He kneaded the dough.",
  "Why did the boy throw his clock out the window? He wanted to see time fly.",
  "Why did the bicycle get a flat tire? It was two-tired.",
  "Why did the computer go to the doctor? It had a virus.",
  "Why did the book go to the doctor? It had a bad spine.",
  "Why did the man put his car in the oven? He wanted a hot rod.",
  "Why did the student bring a ladder to school? He wanted to go to high school.",
  "Why did the boy get a bad grade on his test? He was a little off.",
  "Why did the girl get a bad grade on her test? She was a little off.",
  "What do you call a person who can't make up their mind? A maybe-person.",
  "Why did the man get a job at the zoo? He wanted to work with animals.",
  "Why did the girl get a job at the zoo? She wanted to work with animals.",
  "What did the mother tomato say to the baby tomato? 'Catch up!'",
  "Why do you have to be so loud? You're not a library.",
  "Why did the student get a good grade on his test? He was a little on.",
  "Why did the girl get a good grade on her test? She was a little on.",
  "What do you call a person who is always early? A premature person.",
  "Why did the man get a job at the circus? He wanted to work with clowns.",
  "Why did the girl get a job at the circus? She wanted to work with clowns.",
  "What do you call a person who is always late? A tardy person.",
  "What do you call a belt made out of money? A waist of money.",
  "Why did the man get a job at the farm? He wanted to work with animals.",
  "Why did the girl get a job at the farm? She wanted to work with animals.",
  "What do you call a person who is always sad? A blue person.",
  "Why did the man get a job at the hospital? He wanted to work with doctors.",
  "Why did the girl get a job at the hospital? She wanted to work with doctors.",
  "What do you call a person who is always happy? A yellow person.",
  "Why did the man get a job at the school? He wanted to work with kids.",
  "Why did the girl get a job at the school? She wanted to work with kids.",
  "What do you call a person who is always angry? A red person.",
  "Why did the man get a job at the store? He wanted to work with people.",
  "Why did the girl get a job at the store? She wanted to work with people.",
  "What do you call a person who is always sleepy? A gray person.",
  "Why did the man get a job at the office? He wanted to work with computers.",
  "Why did the girl get a job at the office? She wanted to work with computers.",
  "What do you call a person who is always hungry? A brown person.",
  "Why did the man get a job at the restaurant? He wanted to work with food.",
  "Why did the girl get a job at the restaurant? She wanted to work with food.",
  "What do you call a person who is always thirsty? A clear person.",
  "What is the best way to make a fire with two sticks? Make sure one of them is a match.",
  "I'm so good at sleeping, I can do it with my eyes closed.",
  "I used to have a job at a calendar factory, but I got the sack because I took a couple of days off.",
  "I'm reading a book about anti-gravity. It's impossible to put down.",
  "The shovel was a ground-breaking invention.",
  "I was going to tell a time-traveling joke, but you guys didn't like it.",
  "I'm not a photographer, but I can picture us together.",
  "I don't play fantasy football. It's just a game of chance.",
  "I'm not a fan of spring cleaning. It's just a bunch of dust in the wind.",
  "I'm not a fan of the new Star Wars movies. They're just not the same.",
  "I'm not a fan of the new Marvel movies. They're just not the same.",
  "I'm not a fan of the new DC movies. They're just not the same.",
  "I'm not a fan of the new Harry Potter movies. They're just not the same.",
  "I'm not a fan of the new Lord of the Rings movies. They're just not the same.",
  "I'm not a fan of the new Twilight movies. They're just not the same.",
  "I'm not a fan of the new Hunger Games movies. They're just not the same.",
  "I'm not a fan of the new Divergent movies. They're just not the same.",
  "I'm not a fan of the new Maze Runner movies. They're just not the same.",
  "I'm not a fan of the new Percy Jackson movies. They're just not the same.",
  "I'm not a fan of the new Chronicles of Narnia movies. They're just not the same."
];
